### ISSUE TITLE
Segmentation fault in ~CPU running sample_asm_functions_parameters_vector.asm.bin

### ISSUE THREAD

**Issue by saper** [marekjm/wudoovm#71]
````
Script started on Sat Jul 18 19:15:21 2015
command: gdb --args ./build/bin/vm/cpu tests/compiled/sample_asm_functions_parameters_vector.asm.bin
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) run
Starting program: /home/saper/sw/wudoovm/build/bin/vm/cpu tests/compiled/sample_asm_functions_parameters_vector.asm.bin
[0, 1, 2, 3]

Program received signal SIGSEGV, Segmentation fault.
0x000000000040a7ad in std::__1::__tree_next<std::__1::__tree_node_base<void*>*> (__x=0x7fffffffd618)
    at __tree:68
68      return __x == __x->__parent_->__left_;
(gdb) bt
#0  0x000000000040a7ad in std::__1::__tree_next<std::__1::__tree_node_base<void*>*> (
    __x=0x7fffffffd618) at __tree:68
#1  0x0000000000409419 in ~CPU (this=0x7fffffffd528) at __tree:656
#2  0x000000000040744a in main (argc=2, argv=0x7fffffffe898) at src/front/cpu.cpp:148
(gdb) print __x
$1 = (std::__1::__tree_node_base<void *> *) 0x7fffffffd618
(gdb) print *__x
$2 = {<std::__1::__tree_end_node<std::__1::__tree_node_base<void *> *>> = {__left_ = 0x0},
  __right_ = 0x0, __parent_ = 0x0, __is_black_ = false}
(gdb) The program is running.  Exit anyway? (y or n) y

Script done on Sat Jul 18 19:16:05 2015
````

**Comment by marekjm** [comment]
Fixed by #74.
